# Generated by Django 5.1.15 on 2026-09-03 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(max_length=80)),
                ('right', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], default='moderate', max_length=20)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('form', models.CharField(default='tablet', max_length=40)),
                ('strength', models.CharField(blank=True, max_length=40)),
                ('drug_class', models.CharField(blank=True, max_length=80)),
                ('allergen_groups', models.JSONField(blank=True, default=list)),
                ('rxnorm_code', models.CharField(blank=True, max_length=20)),
                ('is_controlled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'strength', 'form')},
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready for pickup'), ('out_for_delivery', 'Out for delivery'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('fulfilment', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10)),
                ('allergen_alert_triggered', models.BooleanField(default=False)),
                ('safety_report', models.JSONField(blank=True, default=dict)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_pharmacy_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_overrides', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='clinics.pharmacy')),
                ('prescriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(blank=True, max_length=60)),
                ('frequency', models.CharField(blank=True, max_length=60)),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
        ),
    ]
